version: '3'

services:
  api-server:
    container_name: api-server
    image: goalpanzi-api
    environment:
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      OAUTH_APPLE_CLIENT_ID: ${OAUTH_APPLE_CLIENT_ID}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      STORAGE_REGION: ${STORAGE_REGION}
      STORAGE_BUCKET_NAME: ${STORAGE_BUCKET_NAME}
      STORAGE_ACCESS_KEY_ID: ${STORAGE_ACCESS_KEY_ID}
      STORAGE_SECRET_KEY: ${STORAGE_SECRET_KEY}
      ENCODED_FIREBASE_ADMIN_SDK: ${ENCODED_FIREBASE_ADMIN_SDK}
      SLACK_WEBHOOK_URI: ${SLACK_WEBHOOK_URI}
    restart: always
    volumes:
      - ./logs:/logs
    network_mode: host

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - api-server
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    network_mode: host

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    command: "certonly --webroot -w /var/www/certbot --email goalpanzi.team@gmail.com --agree-tos --non-interactive -d mission-mate.kro.kr"
    network_mode: host