spring:
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_DATABASE}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    baseline-version: 0
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3_000
            readTimeout: 3_000

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expires-in-days: 14 # TODO 추후 1로 변경
  refresh-token:
    expires-in-days: 14

springdoc:
  swagger-ui:
    path: /missionmate-docs.html
    query-config-enabled: true
    enabled: true

oauth:
  apple:
    iss: https://appleid.apple.com
    client-id: ${OAUTH_APPLE_CLIENT_ID}

