spring:
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_DATABASE}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    baseline-version: 0

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expires-in: 86400000
  refresh-token:
    expires-in: 1209600000

springdoc:
  swagger-ui:
    path: /missionmate-docs.html
    query-config-enabled: true
    enabled: true

oauth:
  apple:
    iss: https://appleid.apple.com
    client-id: ${OAUTH_APPLE_CLIENT_ID}

